import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import { cookies } from "next/headers";

import { CUSTOMER_AUTH_COOKIES } from "@/app/lib/shopify/customers";
import { CustomerSessionProvider } from "@/components/customer-session-provider";

import "./globals.css";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const cookieStore = await cookies();
  const initialAuthenticated = cookieStore.has(CUSTOMER_AUTH_COOKIES.accessToken);

  return (
    <html lang="fr" className={`${manrope.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <CustomerSessionProvider initialAuthenticated={initialAuthenticated}>
          {children}
        </CustomerSessionProvider>
      </body>
    </html>
  );
}
